name: Publish Docker images
on:
  push:
    tags:
      - "**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
        with:
          fetch-depth: 1

      - name: Get latest tag version
        id: extract-version
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Remove '-docker' suffix from repository_owner
        id: extract-repository-owner
        run: echo "repository_owner=$(echo ${{ github.repository_owner }} | sed 's/-docker//')" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: |-
            docker buildx build \
              --platform linux/arm64,linux/amd64 \
              -t ${{ steps.extract-repository-owner.outputs.repository_owner }}/plantuml:${{ steps.extract-version.outputs.version }} \
              -t ${{ steps.extract-repository-owner.outputs.repository_owner }}/plantuml:latest \
              --push .
